Add Sentry
sixfeetup/cookiecutter-sixiedjango pull request #107
Opened 2023-08-30 16:56 UTC by nvernooy

Add the sentry packages to the requirements file
Add SENTRY_DSN to the kubernetes configmap
Update the README
Closes #76

2023-09-01 09:47 UTC, rochecompaan requested changes

2023-09-01 09:47 UTC, rochecompaan commented on {{cookiecutter.project_slug}}/README.md
> +4. Add code to project
How do you do this? What code?

2023-09-01 09:47 UTC, rochecompaan commented on {{cookiecutter.project_slug}}/README.md
> +For more detailed steps view the [SFU Paper page](https://paper.dropbox.com/doc/Adding-Sentry-to-Projects--B_BGoXS6w~Q8FbkaVOlRooaXAg-7sXkQxTexTtV6qT367VGJ)
You can't include links to private company resources. Cookie-cutter is an open-source project. I recommend we generalize the paper page and add it as documentation to the cookie-cutter.

2023-09-01 09:47 UTC, rochecompaan commented on {{cookiecutter.project_slug}}/k8s/base/django.configmap.yaml
> +  SENTRY_DSN: "CHANGEME_SENTRY_KEY"
I really don't like CHANGEME values ... They often don't get changed.
```suggestion
  SENTRY_DSN: ""
```

2023-09-05 19:38 UTC, rochecompaan approved these changes
Nice!

2023-09-06 12:31 UTC, balavec commented
@rochecompaan do we also want to add sentry to the react frontend?

2023-09-06 12:55 UTC, merged

2023-09-07 11:53 UTC, rochecompaan commented
@balavec yes you're right, we do want to add it to React. @nvernooy do you mind creating an issue to add SENTRY to react since you have already merged this PR?