Merge Django 4.1 branch (at last)
sixfeetup/cookiecutter-sixiedjango pull request #5
Opened 2022-08-24 20:08 UTC by sfu-peter

2022-08-24 20:39 UTC, merged

2022-08-24 21:01 UTC, calvinhp requested changes
Can't wait to use it!

2022-08-24 21:16 UTC, sfu-peter commented on {{cookiecutter.project_slug}}/Makefile
> +up:
The node bits are commented out in the docker-compose anyway?  But I get what you're aiming at.

2022-08-24 21:18 UTC, sfu-peter commented on {{cookiecutter.project_slug}}/docker-compose.yml
> +    command: 'gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker'
The gunicorn command replaces daphne, which is usually a part of channels, which is not supported in this version of the cookiecutter.  The gunicorn/uvicorn command enables django to work in asgi mode without channels, and it's better supported than daphne as well.  But it's true the runserver command should be the uncommented one.  I don't believe runserver_plus can use asgi though?

2022-08-25 13:24 UTC, sfu-peter commented on README.md
> +Creating a new project using this repo:
I don't think this is necessary--for most people, they only use the cookiecutter very rarely (maybe only once?)  Directing them to install the whole pipx infrastructure just to generate a one-off project seems invasive and heavy-handed. The in-project venv is a workable solution that can easily be removed when they've generated their project into another directory...?

2022-08-25 20:07 UTC, calvinhp commented on README.md
> +Creating a new project using this repo:
Adding to the issues list, I'd love to say we are highly opinionated and want the world to discover the join that is `pipx`!